pipeline {
    agent any
    tools {
        jdk 'Java 17' // Use the configured JDK installation
        maven 'Maven' // Use the configured Maven installation
    }
    stages {
        stage('Checkout') {
            steps {
                // Check out the source code from the Git repository
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
		
		stage('Confirm') {
            steps {
                input('Do you want to proceed?')
            }
        }
		
        stage('Build') {
            steps {
                // Build the code using Maven
                bat 'mvn clean install'
		bat 'dir target'
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the JAR file as a build artifact
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
        stage('Docker Build') {
            steps {
            withCredentials([string(credentialsId: 'docker-hub-credentials', variable: 'DOCKER_TOKEN')]) {
	    echo "Docker Token: $DOCKER_TOKEN"
            // Log in to Docker Hub using the API token/secret
            bat 'echo $DOCKER_TOKEN | docker login --username pkofficl --password-stdin'
            
            // Build the Docker image and tag it
            bat 'docker build -t pkofficl/simple-maven-app -f Dockerfile .'
            
            // Push the Docker image to Docker Hub
            bat 'docker push pkofficl/simple-maven-app'
            }
	    }
        }
    }
}
