pipeline {
    agent any
    tools {
        jdk 'Java 17' // Use the configured JDK installation
        maven 'Maven' // Use the configured Maven installation
    }
    stages {
        stage('Checkout') {
            steps {
                // Check out the source code from the Git repository
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
		
		stage('Confirm') {
            steps {
                input('Do you want to proceed?')
            }
        }
		
        stage('Build') {
            steps {
                // Build the code using Maven
                bat 'mvn clean install'
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the JAR file as a build artifact
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
        stage('Docker Build') {
            steps {
                bat 'docker build -t pkofficl/simple-maven-app .'
            }
        }
    }
}
